# Generated by Django 2.1.1 on 2018-09-25 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('one_app', '0002_auto_20180921_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_chek',
            field=models.ManyToManyField(related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
