# Generated by Django 2.1.1 on 2018-10-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one_app', '0004_auto_20180930_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodСategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_app.Category')),
            ],
            options={
                'verbose_name_plural': 'Под категории',
                'verbose_name': 'Под категрия',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_app.PodСategory'),
        ),
    ]
